import HTMLtoDOCX from "html-to-docx";
import PDFDocument from "pdfkit";

interface PolicyDocument {
  companyName: string;
  content: string;
}

export async function generatePDF(policy: PolicyDocument): Promise<Buffer> {
  console.log('[PDF] Starting PDF generation for:', policy.companyName);
  const startTime = Date.now();
  
  return new Promise<Buffer>((resolve, reject) => {
    try {
      // Create PDF document with A4 size
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        bufferPages: true,
      });
      
      // Collect PDF data into buffer
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks);
        const elapsed = Date.now() - startTime;
        console.log(`[PDF] Generated successfully in ${elapsed}ms, size: ${pdfBuffer.length} bytes`);
        resolve(pdfBuffer);
      });
      doc.on('error', (err: Error) => {
        const elapsed = Date.now() - startTime;
        console.error(`[PDF] Generation failed after ${elapsed}ms:`, err);
        reject(err);
      });
      
      // Header
      doc.fontSize(24)
         .fillColor('#059669')
         .text('Privacy Policy', { align: 'center' });
      
      doc.moveDown(0.5);
      
      // Company name
      doc.fontSize(16)
         .fillColor('#374151')
         .text(policy.companyName, { align: 'center' });
      
      doc.moveDown(1);
      
      // Horizontal line
      doc.strokeColor('#e5e7eb')
         .lineWidth(1)
         .moveTo(50, doc.y)
         .lineTo(545, doc.y)
         .stroke();
      
      doc.moveDown(1);
      
      // Policy content (strip HTML tags)
      const plainText = stripHtmlTags(policy.content);
      doc.fontSize(11)
         .fillColor('#000000')
         .text(plainText, {
           align: 'left',
           lineGap: 4,
         });
      
      doc.moveDown(2);
      
      // Footer line
      doc.strokeColor('#e5e7eb')
         .lineWidth(1)
         .moveTo(50, doc.y)
         .lineTo(545, doc.y)
         .stroke();
      
      doc.moveDown(1);
      
      // Footer text
      doc.fontSize(9)
         .fillColor('#6b7280')
         .text('Generated by Sirbal PDPL Compliance Platform', { align: 'center' });
      
      doc.text('www.sirbal.co', { align: 'center' });
      
      // Finalize PDF
      doc.end();
      
    } catch (error) {
      const elapsed = Date.now() - startTime;
      console.error(`[PDF] Generation failed after ${elapsed}ms:`, error);
      reject(error);
    }
  });
}

// Helper function to strip HTML tags for plain text PDF
function stripHtmlTags(html: string): string {
  return html
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>/gi, '\n\n')
    .replace(/<\/div>/gi, '\n')
    .replace(/<\/li>/gi, '\n')
    .replace(/<[^>]*>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

export async function generateDOCX(policy: PolicyDocument): Promise<Buffer> {
  const htmlTemplate = wrapWithDocxTemplate(policy.content, policy.companyName);
  
  const docxBuffer = await HTMLtoDOCX(htmlTemplate, null, {
    table: { row: { cantSplit: true } },
    footer: true,
    pageNumber: true,
    font: 'Cairo',
    margins: {
      top: 1440,
      right: 1440,
      bottom: 1440,
      left: 1440,
    },
  });
  
  return Buffer.from(docxBuffer as ArrayBuffer);
}

function wrapWithPDFTemplate(content: string, companyName: string): string {
  return `
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>سياسة الخصوصية - ${companyName}</title>
    <style>
        /* Use local system fonts - no external loading for faster PDF generation */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', 'Tahoma', 'Arial', 'Helvetica', sans-serif;
            font-size: 12pt;
            line-height: 1.8;
            color: #1a1a1a;
            direction: rtl;
            text-align: right;
        }
        
        .header {
            text-align: center;
            padding-bottom: 20px;
            border-bottom: 2px solid #059669;
            margin-bottom: 30px;
        }
        
        .header h1 {
            color: #059669;
            font-size: 24pt;
            margin-bottom: 10px;
        }
        
        .header .company {
            font-size: 14pt;
            color: #374151;
        }
        
        .content {
            text-align: justify;
        }
        
        h2 {
            color: #059669;
            font-size: 14pt;
            margin-top: 25px;
            margin-bottom: 15px;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 8px;
        }
        
        h3 {
            color: #1f2937;
            font-size: 12pt;
            margin-top: 20px;
            margin-bottom: 10px;
        }
        
        p {
            margin-bottom: 12px;
            text-align: justify;
        }
        
        ul, ol {
            margin-bottom: 15px;
            padding-right: 25px;
        }
        
        li {
            margin-bottom: 8px;
        }
        
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            font-size: 10pt;
            color: #6b7280;
        }
        
        .badge {
            display: inline-block;
            background: #dcfce7;
            color: #166534;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 10pt;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>سياسة الخصوصية</h1>
        <div class="company">${companyName}</div>
    </div>
    
    <div class="content">
        ${content}
    </div>
    
    <div class="footer">
        <p>تم إنشاء هذه السياسة بواسطة منصة سِرْبَال للامتثال لنظام حماية البيانات الشخصية</p>
        <p>www.sirbal.co</p>
    </div>
</body>
</html>
  `;
}

function wrapWithDocxTemplate(content: string, companyName: string): string {
  return `
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>سياسة الخصوصية - ${companyName}</title>
</head>
<body style="font-family: Cairo, Arial, sans-serif; direction: rtl; text-align: right; line-height: 1.8;">
    <h1 style="text-align: center; color: #059669;">سياسة الخصوصية</h1>
    <h2 style="text-align: center; color: #374151;">${companyName}</h2>
    <hr style="margin: 20px 0; border: 1px solid #e5e7eb;">
    
    ${content}
    
    <hr style="margin: 30px 0; border: 1px solid #e5e7eb;">
    <p style="text-align: center; color: #6b7280; font-size: 10pt;">
        تم إنشاء هذه السياسة بواسطة منصة سِرْبَال للامتثال لنظام حماية البيانات الشخصية<br>
        www.sirbal.co
    </p>
</body>
</html>
  `;
}
